"""surql - Code-first database toolkit for SurrealDB."""

from surql.connection import (
  ConnectionConfig,
  ConnectionError,
  ContextError,
  DatabaseClient,
  DatabaseError,
  QueryError,
  Transaction,
  TransactionError,
  TransactionState,
  clear_db,
  connection_override,
  connection_scope,
  get_client,
  get_db,
  has_db,
  set_db,
  transaction,
)
from surql.query import (
  CountResult,
  ListResult,
  Query,
  RecordResult,
  aggregate_records,
  as_,
  count,
  count_if,
  count_records,
  create_record,
  create_records,
  create_relation,
  create_typed,
  delete,
  delete_record,
  delete_records,
  execute_query,
  exists,
  extract_many,
  extract_one,
  extract_result,
  extract_scalar,
  fetch_all,
  fetch_many,
  fetch_one,
  first,
  get_record,
  get_related_records,
  get_typed,
  has_result,
  has_results,
  insert,
  last,
  math_abs_fn,
  math_ceil_fn,
  math_floor_fn,
  math_max,
  math_max_fn,
  math_mean,
  math_mean_fn,
  math_min,
  math_min_fn,
  math_round_fn,
  math_sum,
  math_sum_fn,
  merge_record,
  query_records,
  query_typed,
  relate,
  remove_relation,
  select,
  similarity_search_query,
  string_concat,
  string_len,
  string_lower,
  string_upper,
  time_now_fn,
  traverse,
  update,
  update_record,
  update_typed,
  upsert,
  upsert_record,
  upsert_typed,
)
from surql.types import (
  Operator,
  RecordID,
  RecordRef,
  SurrealFn,
  and_,
  contains,
  eq,
  gt,
  gte,
  lt,
  lte,
  ne,
  not_,
  or_,
  record_ref,
  surql_fn,
  type_record,
  type_thing,
)

__version__ = '1.2.1'

__all__ = [
  # Configuration
  'ConnectionConfig',
  # Client
  'DatabaseClient',
  'get_client',
  # Exceptions
  'DatabaseError',
  'ConnectionError',
  'QueryError',
  'TransactionError',
  'ContextError',
  # Transaction
  'Transaction',
  'TransactionState',
  'transaction',
  # Context
  'get_db',
  'set_db',
  'clear_db',
  'has_db',
  'connection_scope',
  'connection_override',
  # Query builder
  'Query',
  'select',
  'similarity_search_query',
  'insert',
  'update',
  'delete',
  'upsert',
  'relate',
  # Aggregation functions
  'count',
  'math_mean',
  'math_sum',
  'math_max',
  'math_min',
  'as_',
  # SurrealQL function factories (SurrealFn)
  'time_now_fn',
  'math_mean_fn',
  'math_sum_fn',
  'math_min_fn',
  'math_max_fn',
  'math_ceil_fn',
  'math_floor_fn',
  'math_round_fn',
  'math_abs_fn',
  'string_len',
  'string_concat',
  'string_lower',
  'string_upper',
  'count_if',
  # Query execution
  'execute_query',
  'fetch_one',
  'fetch_all',
  'fetch_many',
  # CRUD operations
  'create_record',
  'create_records',
  'get_record',
  'update_record',
  'merge_record',
  'upsert_record',
  'delete_record',
  'delete_records',
  'query_records',
  'count_records',
  'aggregate_records',
  'exists',
  'first',
  'last',
  # Typed CRUD operations
  'create_typed',
  'get_typed',
  'query_typed',
  'update_typed',
  'upsert_typed',
  # Graph operations
  'traverse',
  'create_relation',
  'remove_relation',
  'get_related_records',
  # Results
  'RecordResult',
  'ListResult',
  'CountResult',
  # Result extraction utilities
  'extract_result',
  'extract_one',
  'extract_scalar',
  'extract_many',
  'has_results',
  'has_result',
  # Types
  'RecordID',
  'RecordRef',
  'record_ref',
  'SurrealFn',
  'surql_fn',
  'type_record',
  'type_thing',
  'Operator',
  'eq',
  'ne',
  'gt',
  'gte',
  'lt',
  'lte',
  'contains',
  'and_',
  'or_',
  'not_',
]
