"""reverie - Code-first database toolkit for SurrealDB."""

from reverie.connection import (
  ConnectionConfig,
  ConnectionError,
  ContextError,
  DatabaseClient,
  DatabaseError,
  QueryError,
  Transaction,
  TransactionError,
  TransactionState,
  clear_db,
  connection_override,
  connection_scope,
  get_client,
  get_db,
  has_db,
  set_db,
  transaction,
)
from reverie.query import (
  CountResult,
  ListResult,
  Query,
  RecordResult,
  count_records,
  create_record,
  create_records,
  create_relation,
  delete,
  delete_record,
  execute_query,
  exists,
  fetch_all,
  fetch_many,
  fetch_one,
  first,
  get_record,
  get_related_records,
  insert,
  last,
  merge_record,
  query_records,
  relate,
  remove_relation,
  select,
  traverse,
  update,
  update_record,
)
from reverie.types import (
  Operator,
  RecordID,
  and_,
  contains,
  eq,
  gt,
  gte,
  lt,
  lte,
  ne,
  not_,
  or_,
)

__version__ = '0.1.0'

__all__ = [
  # Configuration
  'ConnectionConfig',
  # Client
  'DatabaseClient',
  'get_client',
  # Exceptions
  'DatabaseError',
  'ConnectionError',
  'QueryError',
  'TransactionError',
  'ContextError',
  # Transaction
  'Transaction',
  'TransactionState',
  'transaction',
  # Context
  'get_db',
  'set_db',
  'clear_db',
  'has_db',
  'connection_scope',
  'connection_override',
  # Query builder
  'Query',
  'select',
  'insert',
  'update',
  'delete',
  'relate',
  # Query execution
  'execute_query',
  'fetch_one',
  'fetch_all',
  'fetch_many',
  # CRUD operations
  'create_record',
  'create_records',
  'get_record',
  'update_record',
  'merge_record',
  'delete_record',
  'query_records',
  'count_records',
  'exists',
  'first',
  'last',
  # Graph operations
  'traverse',
  'create_relation',
  'remove_relation',
  'get_related_records',
  # Results
  'RecordResult',
  'ListResult',
  'CountResult',
  # Types
  'RecordID',
  'Operator',
  'eq',
  'ne',
  'gt',
  'gte',
  'lt',
  'lte',
  'contains',
  'and_',
  'or_',
  'not_',
]
