"""Schema definition layer for reverie ORM.

This package provides functions and types for defining table and edge schemas
in a functional, composable way.
"""

from reverie.schema.edge import (
  EdgeDefinition,
  EdgeMode,
  bidirectional_edge,
  edge_schema,
  typed_edge,
  with_edge_events,
  with_edge_fields,
  with_edge_indexes,
  with_edge_permissions,
  with_from_table,
  with_to_table,
)
from reverie.schema.fields import (
  FieldDefinition,
  FieldType,
  array_field,
  bool_field,
  computed_field,
  datetime_field,
  field,
  float_field,
  int_field,
  object_field,
  record_field,
  string_field,
)
from reverie.schema.parser import (
  SchemaParseError,
  parse_db_info,
  parse_table_info,
)
from reverie.schema.registry import (
  SchemaRegistry,
  clear_registry,
  get_registered_edges,
  get_registered_tables,
  get_registry,
  register_edge,
  register_table,
)
from reverie.schema.table import (
  EventDefinition,
  IndexDefinition,
  IndexType,
  MTreeDistanceType,
  MTreeVectorType,
  TableDefinition,
  TableMode,
  event,
  index,
  mtree_index,
  search_index,
  set_mode,
  table_schema,
  unique_index,
  with_events,
  with_fields,
  with_indexes,
  with_permissions,
)

__all__ = [
  # Field types and definitions
  'FieldType',
  'FieldDefinition',
  'field',
  'string_field',
  'int_field',
  'float_field',
  'bool_field',
  'datetime_field',
  'record_field',
  'array_field',
  'object_field',
  'computed_field',
  # Table schema
  'TableMode',
  'IndexType',
  'MTreeDistanceType',
  'MTreeVectorType',
  'IndexDefinition',
  'EventDefinition',
  'TableDefinition',
  'table_schema',
  'index',
  'unique_index',
  'search_index',
  'mtree_index',
  'event',
  'with_fields',
  'with_indexes',
  'with_events',
  'with_permissions',
  'set_mode',
  # Edge schema
  'EdgeMode',
  'EdgeDefinition',
  'edge_schema',
  'with_from_table',
  'with_to_table',
  'with_edge_fields',
  'with_edge_indexes',
  'with_edge_events',
  'with_edge_permissions',
  'bidirectional_edge',
  'typed_edge',
  # Registry
  'SchemaRegistry',
  'get_registry',
  'register_table',
  'register_edge',
  'clear_registry',
  'get_registered_tables',
  'get_registered_edges',
  # Parser
  'SchemaParseError',
  'parse_table_info',
  'parse_db_info',
]
