"""Query builder and ORM layer for SurrealDB.

This module provides a complete query building and ORM system with:
- Immutable query builder with fluent API
- Type-safe query expressions
- Async query execution with result deserialization
- High-level CRUD operations
- Graph traversal utilities
- Result wrapper classes
- Batch operation helpers
"""

from surql.query.batch import (  # Batch operations
  build_relate_query,
  build_upsert_query,
  delete_many,
  insert_many,
  relate_many,
  upsert_many,
)
from surql.query.builder import Query  # Query builder
from surql.query.crud import (  # CRUD operations
  aggregate_records,
  count_records,
  create_record,
  create_records,
  delete_record,
  delete_records,
  exists,
  first,
  get_record,
  last,
  merge_record,
  query_records,
  query_records_wrapped,
  update_record,
  upsert_record,
)
from surql.query.executor import (  # Query executor
  execute_query,
  execute_raw,
  execute_raw_typed,
  fetch_all,
  fetch_many,
  fetch_one,
  fetch_record,
  fetch_records,
)
from surql.query.expressions import (  # Query expressions
  Expression,
  FieldExpression,
  FunctionExpression,
  ValueExpression,
  abs_,
  array_contains,
  array_length,
  as_,
  avg,
  cast,
  ceil,
  concat,
  count,
  field,
  floor,
  func,
  lower,
  math_max,
  math_mean,
  math_min,
  math_sum,
  max_,
  min_,
  raw,
  round_,
  sum_,
  time_format,
  time_now,
  type_is,
  upper,
  value,
)
from surql.query.functions import (  # SurrealQL function factories (SurrealFn)
  count_if,
  math_abs_fn,
  math_ceil_fn,
  math_floor_fn,
  math_max_fn,
  math_mean_fn,
  math_min_fn,
  math_round_fn,
  math_sum_fn,
  string_concat,
  string_len,
  string_lower,
  string_upper,
  time_now_fn,
)
from surql.query.graph import (  # Graph operations
  count_related,
  get_incoming_edges,
  get_outgoing_edges,
  get_related_records,
  shortest_path,
  traverse,
  traverse_with_depth,
)
from surql.query.graph import (
  relate as create_relation,
)
from surql.query.graph import (
  unrelate as remove_relation,
)
from surql.query.helpers import (  # Query builder helpers and shared types
  ReturnFormat,
  VectorDistanceType,
  delete,
  from_table,
  insert,
  limit,
  offset,
  order_by,
  relate,
  select,
  similarity_search_query,
  update,
  upsert,
  vector_search_query,
  where,
)
from surql.query.hints import (  # Query optimization hints
  ExplainHint,
  FetchHint,
  HintRenderer,
  IndexHint,
  ParallelHint,
  QueryHint,
  TimeoutHint,
  merge_hints,
  render_hints,
  validate_hint,
)
from surql.query.results import (  # Result wrappers and utilities
  AggregateResult,
  CountResult,
  ListResult,
  PageInfo,
  PaginatedResult,
  QueryResult,
  RecordResult,
  aggregate,
  count_result,
  extract_many,
  extract_one,
  extract_result,
  extract_scalar,
  has_result,
  has_results,
  paginated,
  record,
  records,
  success,
)
from surql.query.typed import (  # Typed CRUD operations
  create_typed,
  get_typed,
  query_typed,
  update_typed,
  upsert_typed,
)

__all__ = [
  # Query builder
  'Query',
  'select',
  'from_table',
  'where',
  'order_by',
  'limit',
  'offset',
  'insert',
  'update',
  'delete',
  'upsert',
  'relate',
  'vector_search_query',
  'similarity_search_query',
  'VectorDistanceType',
  # Query hints
  'QueryHint',
  'IndexHint',
  'ParallelHint',
  'TimeoutHint',
  'FetchHint',
  'ExplainHint',
  'HintRenderer',
  'validate_hint',
  'merge_hints',
  'render_hints',
  # Query expressions
  'Expression',
  'FieldExpression',
  'ValueExpression',
  'FunctionExpression',
  'field',
  'value',
  'func',
  'count',
  'sum_',
  'avg',
  'min_',
  'max_',
  'upper',
  'lower',
  'concat',
  'array_length',
  'array_contains',
  'abs_',
  'ceil',
  'floor',
  'round_',
  'time_now',
  'time_format',
  'type_is',
  'cast',
  'as_',
  'raw',
  'math_mean',
  'math_sum',
  'math_max',
  'math_min',
  # SurrealQL function factories (SurrealFn)
  'time_now_fn',
  'math_mean_fn',
  'math_sum_fn',
  'math_min_fn',
  'math_max_fn',
  'math_ceil_fn',
  'math_floor_fn',
  'math_round_fn',
  'math_abs_fn',
  'string_len',
  'string_concat',
  'string_lower',
  'string_upper',
  'count_if',
  # Query executor
  'execute_query',
  'fetch_one',
  'fetch_all',
  'fetch_many',
  'fetch_record',
  'fetch_records',
  'execute_raw',
  'execute_raw_typed',
  # CRUD operations
  'create_record',
  'create_records',
  'get_record',
  'update_record',
  'merge_record',
  'delete_record',
  'delete_records',
  'query_records',
  'query_records_wrapped',
  'upsert_record',
  'count_records',
  'aggregate_records',
  'exists',
  'first',
  'last',
  # Batch operations
  'upsert_many',
  'relate_many',
  'insert_many',
  'delete_many',
  'build_upsert_query',
  'build_relate_query',
  # Graph operations
  'traverse',
  'traverse_with_depth',
  'create_relation',
  'remove_relation',
  'get_outgoing_edges',
  'get_incoming_edges',
  'get_related_records',
  'count_related',
  'shortest_path',
  # Result wrappers
  'QueryResult',
  'RecordResult',
  'ListResult',
  'CountResult',
  'AggregateResult',
  'PageInfo',
  'PaginatedResult',
  'success',
  'record',
  'records',
  'count_result',
  'aggregate',
  'paginated',
  # Result extraction utilities
  'extract_result',
  'extract_one',
  'extract_scalar',
  'extract_many',
  'has_results',
  'has_result',
  # Typed CRUD operations
  'create_typed',
  'get_typed',
  'query_typed',
  'update_typed',
  'upsert_typed',
  # Return format
  'ReturnFormat',
]
