"""Schema definition layer for surql ORM.

This package provides functions and types for defining table, edge, and access
schemas in a functional, composable way.
"""

from surql.schema.access import (
  AccessDefinition,
  AccessType,
  JwtConfig,
  RecordAccessConfig,
  access_schema,
  jwt_access,
  record_access,
)
from surql.schema.analyzer import (
  AnalyzerDefinition,
  TokenFilter,
  TokenFilterType,
  Tokenizer,
  analyzer,
  ascii_filter,
  edge_ngram,
  lowercase,
  ngram,
  snowball,
  standard_analyzer,
  uppercase,
)
from surql.schema.bucket import (
  BucketDefinition,
  bucket_schema,
  file_bucket,
  memory_bucket,
)
from surql.schema.edge import (
  EdgeDefinition,
  EdgeMode,
  bidirectional_edge,
  edge_schema,
  typed_edge,
  with_edge_events,
  with_edge_fields,
  with_edge_indexes,
  with_edge_permissions,
  with_from_table,
  with_to_table,
)
from surql.schema.fields import (
  FieldDefinition,
  FieldType,
  array_field,
  bool_field,
  bytes_field,
  computed_field,
  datetime_field,
  field,
  file_field,
  float_field,
  int_field,
  object_field,
  record_field,
  string_field,
)
from surql.schema.parser import (
  SchemaParseError,
  parse_bucket_info,
  parse_db_buckets,
  parse_db_info,
  parse_edge_info,
  parse_table_info,
)
from surql.schema.registry import (
  SchemaRegistry,
  clear_registry,
  get_registered_buckets,
  get_registered_edges,
  get_registered_tables,
  get_registry,
  register_bucket,
  register_edge,
  register_table,
)
from surql.schema.sql import (
  generate_access_sql,
  generate_alter_bucket_sql,
  generate_analyzer_sql,
  generate_analyzer_sql_with_options,
  generate_bucket_sql,
  generate_edge_sql,
  generate_remove_bucket_sql,
  generate_schema_sql,
  generate_table_sql,
)
from surql.schema.table import (
  EventDefinition,
  HnswDistanceType,
  IndexDefinition,
  IndexType,
  MTreeDistanceType,
  MTreeVectorType,
  TableDefinition,
  TableMode,
  bm25_index,
  event,
  hnsw_index,
  index,
  mtree_index,
  search_index,
  set_mode,
  table_schema,
  unique_index,
  with_events,
  with_fields,
  with_indexes,
  with_permissions,
)
from surql.schema.themes import (
  DARK_THEME,
  FOREST_THEME,
  MINIMAL_THEME,
  MODERN_THEME,
  ASCIITheme,
  ColorScheme,
  GraphVizTheme,
  MermaidTheme,
  Theme,
  get_theme,
  list_themes,
)

__all__ = [
  # Field types and definitions
  'FieldType',
  'FieldDefinition',
  'field',
  'string_field',
  'int_field',
  'float_field',
  'bool_field',
  'datetime_field',
  'record_field',
  'array_field',
  'object_field',
  'file_field',
  'bytes_field',
  'computed_field',
  # Table schema
  'TableMode',
  'IndexType',
  'MTreeDistanceType',
  'MTreeVectorType',
  'HnswDistanceType',
  'IndexDefinition',
  'EventDefinition',
  'TableDefinition',
  'table_schema',
  'index',
  'unique_index',
  'search_index',
  'bm25_index',
  'mtree_index',
  'hnsw_index',
  'event',
  'with_fields',
  'with_indexes',
  'with_events',
  'with_permissions',
  'set_mode',
  # Full-text analyzers
  'AnalyzerDefinition',
  'Tokenizer',
  'TokenFilter',
  'TokenFilterType',
  'analyzer',
  'standard_analyzer',
  'ascii_filter',
  'lowercase',
  'uppercase',
  'edge_ngram',
  'ngram',
  'snowball',
  # Edge schema
  'EdgeMode',
  'EdgeDefinition',
  'edge_schema',
  'with_from_table',
  'with_to_table',
  'with_edge_fields',
  'with_edge_indexes',
  'with_edge_events',
  'with_edge_permissions',
  'bidirectional_edge',
  'typed_edge',
  # Registry
  'SchemaRegistry',
  'get_registry',
  'register_table',
  'register_edge',
  'register_bucket',
  'clear_registry',
  'get_registered_tables',
  'get_registered_edges',
  'get_registered_buckets',
  # Parser
  'SchemaParseError',
  'parse_table_info',
  'parse_edge_info',
  'parse_db_info',
  'parse_bucket_info',
  'parse_db_buckets',
  # Themes
  'ColorScheme',
  'GraphVizTheme',
  'MermaidTheme',
  'ASCIITheme',
  'Theme',
  'MODERN_THEME',
  'DARK_THEME',
  'FOREST_THEME',
  'MINIMAL_THEME',
  'get_theme',
  'list_themes',
  # Access schema
  'AccessType',
  'JwtConfig',
  'RecordAccessConfig',
  'AccessDefinition',
  'access_schema',
  'jwt_access',
  'record_access',
  # Bucket schema
  'BucketDefinition',
  'bucket_schema',
  'memory_bucket',
  'file_bucket',
  # SQL generation
  'generate_table_sql',
  'generate_edge_sql',
  'generate_access_sql',
  'generate_analyzer_sql',
  'generate_analyzer_sql_with_options',
  'generate_schema_sql',
  'generate_bucket_sql',
  'generate_remove_bucket_sql',
  'generate_alter_bucket_sql',
]
